### DISCUSSION TITLE
Lavalink Music problem

### DISCUSSION THREAD

**Discussion by MrTabaOfficial** [lavalink-devs/Lavalink#1080] [Q&A] [answered]
Guys can u explain me something is it Lavalink problem ? in my bot working everything good. it could be Play music but 2 days ago it stopped to playing. im using last version of Lavalink and last youtube source. its doing this when i play bot comes in voice and in 1 ms its leaving. here is log of lavalink

````
2024-07-21T12:49:39.632Z  INFO 29 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/loadtracks?identifier=ytsearch%3A1%2C2%2C3, client=ipaddress
2024-07-21T12:49:40.082Z  INFO 29 --- [XNIO-1 task-2] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8509w27w3ej3gotm/players/1058011809338114108?noReplace=false, client=ipaddress, payload={"track":{"encoded":"QAAA4wMASlNvZmlhIFJleWVzIC0gMSwgMiwgMyAoZmVhdC4gSmFzb24gRGVydWxvICYgRGUgTGEgR2hldHRvKSBbT2ZmaWNpYWwgVmlkZW9dAAtTb2ZpYSBSZXllcwAAAAAAAxj4AAtwMDNUSUdxRWM4bwABACtodHRwczovL3d3dy55b3V0dWJlLmNvbS93YXRjaD92PXAwM1RJR3FFYzhvAQAwaHR0cHM6Ly9pLnl0aW1nLmNvbS92aS9wMDNUSUdxRWM4by9tcWRlZmF1bHQuanBnAAAHeW91dHViZQAAAAAAAAAA"}}
2024-07-21T12:49:40.087Z  INFO 29 --- [XNIO-1 task-4] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8509w27w3ej3gotm/players/1058011809338114108?noReplace=false, client=ipaddress, payload={"volume":60}
2024-07-21T12:49:40.694Z  INFO 29 --- [XNIO-1 task-4] l.server.io.RequestLoggingFilter         : PATCH /v4/sessions/8509w27w3ej3gotm/players/1058011809338114108?noReplace=false, client=ipaddress, payload={"voice":{"token":"ef43fbe452377f90","endpoint":"bucharest5334.discord.media:443","sessionId":"e405026e37b82481be234a264ae76743"}}
2024-07-21T12:49:41.084Z  INFO 29 --- [XNIO-1 task-4] l.server.io.RequestLoggingFilter         : DELETE /v4/sessions/8509w27w3ej3gotm/players/1058011809338114108, client=ipaddress
````

**Comment by devoxin** [comment]
When seeking support it's generally a good idea to provide debug logs as well as your configuration.

**Reply by MrTabaOfficial** [reply]
```
server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false # Whether to enable HTTP/2 support
plugins:
  youtube:
      enabled: true 
      allowSearch: true 
      allowDirectVideoIds: true 
      allowDirectPlaylistIds: true 

      clients:
		- MUSIC
      	- ANDROID_TESTSUITE
      	- WEB

      WEB: 
        playback: true
      TVHTML5EMBEDDED:
        
        playlistLoading: true
        videoLoading: false 
        searching: false # Disables the ability to search for videos for this client.
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.4.0"
      snapshot: false # Set to true if you want to use a snapshot version.
  server:
    password: "pwd1234"
    sources:
      # The default Youtube source is now deprecated and won't receive further updates. Please use https://github.com/lavalink-devs/youtube-source#plugin instead.
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
    #youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
      #email: "" # Email of Google account
      #password: "" # Password of Google account
    #httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
      #proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
      #proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
      #proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
      #proxyPassword: "" # Password for basic authentication

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000


  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
```
