### ISSUE TITLE
Setting via application.yml is deprecated?

### ISSUE THREAD

**Issue by opentypefont** [lavalink-devs/Lavalink#1133]
I'm using docker with compose on my main server, but I found it doesn't following application.yml settings that I put in container by volume binding.
### `docker-compose.yml`
```yml
services:
  lavalink:
    image: fredboat/lavalink:4.0.8
    container_name: lavalink
    restart: unless-stopped
    tty: true
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
    expose:
      - 2333
    ports:
      - "2333:2333"
  ```
### `application.yml`
```yml
server: # REST and WS server
  port: 2333
  address: 0.0.0.0
  http2:
    enabled: false # Whether to enable HTTP/2 support
plugins:
  youtube:
    enabled: true # Whether this source can be used.
    allowSearch: true # Whether "ytsearch:" and "ytmsearch:" can be used.
    allowDirectVideoIds: true # Whether just video IDs can match. If false, only complete URLs will be loaded.
    allowDirectPlaylistIds: true # Whether just playlist IDs can match. If false, only complete URLs will be loaded.
    # The clients to use for track loading. See below for a list of valid clients.
    # Clients are queried in the order they are given (so the first client is queried first and so on...)
    clients:
      - MUSIC
      - TVHTML5EMBEDDED
      - ANDROID_MUSIC
      - WEB
      - WEBEMBEDDED
      - ANDROID
      - ANDROID_LITE
      - MEDIA_CONNECT
      - IOS
    pot:
      visitorData: <visitorData>
      token: <token>
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.4"
      snapshot: false # Set to true if you want to use a snapshot version.
  server:
    password: <password>
    sources:
      # The default Youtube source is now deprecated and won't receive further updates. Please use https://github.com/lavalink-devs/youtube-source#plugin instead.
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    bufferDurationMs: 100 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: HIGH # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: false
    soundcloudSearchEnabled: true
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includeQueryString: true
    includePayload: true
    maxPayloadLength: 10000

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30

```
The Lavalink instance doesn't install youtube-source plugin and be authorized by `<password>`. Moreover, I found this warning although I disabled default youtube source.
```
2025-02-11T13:08:33.366+09:00  WARN 49037 --- [Lavalink] [           main] l.s.config.AudioPlayerConfiguration      : The default Youtube source is now deprecated and won't receive further updates.
You should use the new Youtube source plugin instead.
https://github.com/lavalink-devs/youtube-source#plugin.
To disable this warning, set 'lavalink.server.sources.youtube' to false in your application.yml.
```
And it is the same as on my MacBook Air M1 with this folder structure.
```
❯ ll
total 165904
-rw-r--r--   1 opentypefont  staff  76785730 Feb 11 13:08 Lavalink.jar
-rw-r--r--   1 opentypefont  staff      4754 Feb 11 13:05 application.yml
drwxr-xr-x@ 15 opentypefont  staff       480 Feb 11 13:02 logs
drwxr-xr-x   2 opentypefont  staff        64 Feb 11 13:03 plugins
```
But something different on MacBook, the older version of youtube-source plugin was downloaded in plugins folder and it recognized by Lavalink like this.
```
2025-02-11T13:02:13.933+09:00  WARN 48083 --- [Lavalink] [           main] d.l.youtube.plugin.ClientProvider        : Failed to resolve WEBEMBEDDED into a Client
2025-02-11T13:02:13.933+09:00  WARN 48083 --- [Lavalink] [           main] dev.lavalink.youtube.clients.Android     : ANDROID is broken with no known fix. It is no longer advised to use this client.
2025-02-11T13:02:13.936+09:00  INFO 48083 --- [Lavalink] [           main] d.l.youtube.plugin.YoutubePluginLoader   : YouTube source initialised with clients: WEB_REMIX, TVHTML5_SIMPLY_EMBEDDED_PLAYER, ANDROID_MUSIC, WEB, ANDROID, ANDROID_LITE, MEDIA_CONNECT_FRONTEND, IOS 
```
I tested set password via environment variable and as it worked, I thought that settings via application.yml might be deprecated but there are no mention about that. I don't know what the problem is and I would appreciate your help with this issue.
