### ISSUE TITLE
Error with YouTube search/playback using IPV6 Rotation

### ISSUE THREAD

**Issue by 230Daniel** [lavalink-devs/Lavalink#306]
## Description
I have enabled IPV6 rotation using the following config options:
```
ratelimit:
      ipBlocks: ["2001:41d0:a:7b33:3460:6b77:c818:0/123"]
      #excludedIps: ["..."]
      strategy: "RotateOnBan"
      searchTriggersFail: true
      retryLimit: 0
```
but YouTube playback is erroring. The same error occurs when performing a search. In fact, I never have a case where Lavalink plays a track without searching first so it is likely just search.

YouTube playback and search works fine without IPV6 rotation enabled. Soundcloud playback works both with IPV6 rotation enabled and with IPV6 rotation disabled.

[Logs](https://hastebin.com/avikohimac.txt) (Also attached as a file)
[spring.log](https://github.com/Frederikam/Lavalink/files/4719912/spring.log)

## Version info
**Client used:** Victoria 5.1.6 (C#)

Output of `java -version`:
```
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)
```

Output of `java -jar Lavalink.jar --version`:
```
Version:        606fbf3ca475d39e15183fe91ab0149fa17d0fe9-SNAPSHOT
Build:          1061
Build time:     29.05.2020 10:23:19 UTC
Branch          master
Commit:         606fbf3
Commit time:    29.05.2020 10:19:10 UTC
JVM:            11.0.7
Lavaplayer      1.3.49
```
