### ISSUE TITLE
(node:4051) UnhandledPromiseRejectionWarning: Error: No available nodes.

### ISSUE THREAD

**Issue by KrabbyBuckets** [lavalink-devs/Lavalink#483]
## Description

It throws this error when i try to make a `!play` command.

## Version info
Erela.js - I used this to connect with lavalink

15.0.1
```

server: # REST and WS server
  port: 9000
  address: 0.0.0.0
lavalink:
  server:
    password: ""
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
```

Version:        3.3.2.5
Build:          1222
Build time:     11.04.2021 08:07:27 UTC
Branch          master
Commit time:    09.04.2021 17:14:27 UTC
JVM:            15.0.1
Lavaplayer      1.3.76
