### ISSUE TITLE
ERROR CONNECTION REFUSED Lavalink server

### ISSUE THREAD

**Issue by PatalJunior** [lavalink-devs/Lavalink#536]
## Description
Cannot connect to Lavalink, but I used to
```
Info: Lavalink: Node Main had an error: connect ECONNREFUSED 127.0.0.1:2333
```
If I try to open localhost:2333 it gives a ERR_CONNECTION_REFUSED

## Version info
**Client used:** NodeJS

Output of `java -version`:
```
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

```
How to get logs ?
Cannot find file with them.

Version:        3.3.2.5
Build:          1222
Build time:     11.04.2021 08:07:27 UTC
Branch          master
Commit:         7b914f2
Commit time:    09.04.2021 17:14:27 UTC
JVM:            13.0.2
Lavaplayer      1.3.76

**Comment by topi314** [comment]
you are prob using the wrong password

**Comment by PatalJunior** [comment]
Upon checking passwords are the same.

It used to work, and then it stopped, so I don't think it would be the password.

``This is my application.yml``

```yml
server: # REST and WS server
  port: 2333
  address: 127.0.0.1
lavalink:
  server:
    password: "mypasswordforsure"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."] # list of ip blocks
      #excludedIps: ["...", "..."] # ips which should be explicit excluded from usage by lavalink
      #strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
    
```
