### ISSUE TITLE
Port already in use Docker

### ISSUE THREAD

**Issue by ThatAnonyG** [lavalink-devs/Lavalink#659]
I am using the default Docker image from `fredboat/lavalink:master`.

This is my application.yaml
```yaml
server: # REST and WS server
  port: 2333
  address: <server_public_ip>
lavalink:
  server:
    password: <passwd>
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: [1.0.0.0/8, ...] # list of ip blocks
      #excludedIps: [..., ...] # ips which should be explicit excluded from usage by lavalink
      #strategy: RotateOnBan # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
      #searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
      #retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: 
  environment: 
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
```

I am trying to run it using the command:
```
docker run -v ~/application.yaml:/opt/Lavalink/application.yaml -p 2333:2333 --name lavalink fredboat/lavalink:master
```

But no matter what I try I get the error saying Port is currently in use. I have tried on my Raspberry Pi with the same Dockerfile just and a arm64 jdk. Same thing. I tried on my Digital Ocean VPS, same issue. I have tried over 10 different ports and still same thing. But when I do not provide any config it works just fine.
