### ISSUE TITLE
Adding example docker-compose file?

### ISSUE THREAD

**Issue by Macleykun** [lavalink-devs/Lavalink#687]
Heyo!

For lavamusic i made a docker-compose and partly made the lavalink service:

```yml
version: "3.8"
services:
  lavalink:
    container_name: Lavalink
    image: fredboat/lavalink:dev
    environment:
      SERVER_PORT: 2333
      SERVER_ADDRESS: 0.0.0.0
      LAVALINK_SERVER_PASSWORD: "youshallnotpass"
      LAVALINK_SERVER_SOURCES_YOUTUBE: 'true'
      LAVALINK_SERVER_SOURCES_BANDCAMP: 'true'
      LAVALINK_SERVER_SOURCES_SOUNDCLOUD: 'true'
      LAVALINK_SERVER_SOURCES_TWITCH: 'true'
      LAVALINK_SERVER_SOURCES_VIMEO: 'true'
      LAVALINK_SERVER_SOURCES_HTTP: 'true'
      LAVALINK_SERVER_SOURCES_LOCAL: 'false'
      LAVALINK_SERVER_BUFFER_DURATION_MS: 400
      LAVALINK_SERVER_FRAME_BUFFER_DURATIONS_MS: 5000
      LAVALINK_SERVER_TRACK_STRUCK_THRESHOLD_MS: 10000
      LAVALINK_SERVER_YOUTUBE_PLAYLIST_LOAD_LIMIT: 6
      LAVALINK_SERVER_PLAYER_UPDATE_INTERVAL: 5
      LAVALINK_SERVER_YOUTUBE_SEARCH_ENABLED: 'true'
      LAVALINK_SERVER_SOUNDCLOUD_SEARCH_ENABLED: 'true'
      #LAVALINK_SERVER_YOUTUBE_CONFIG_EMAIL:
      #LAVALINK_SERVER_YOUTUBE_CONFIG_PASSWORD:
      LAVALINK_SERVER_SENTRY_DSN: ""
    restart: on-failure
```

I can make it so that you don't need to use a volume to only mount the config. People can instead fill in the docker-compose or if preferred, I can refer to a .env file and make it an example where this compose refers to.

Is this something that you guys would be willing to merge? The only downside is that you technically need to keep the compose/env example up-to-date whenever you add/remove from the application.yml.

Looking forward to your reply!
