### ISSUE TITLE
[Feature Request] Disable filters via config file

### ISSUE THREAD

**Issue by Drapersniper** [lavalink-devs/Lavalink#771]
Currently, hosts who don't wish to have filters enabled must create an HTTP blackhole with Nginx, etc, or some other method to redirect requests which would otherwise apply a filter to the player.

Filters can significantly increase the resource usage of a player, as such it would be great if there was a native and supported method to do this (and ideally report that this is done so libs can know ahead of time instead of assuming a filter was applied when it isn't (`/v3/info`) 

Something like the following
```yaml
lavalink:
  server:
    filters: false
```
alternatively
```yaml
lavalink:
  server:
    filters: 
      volume: false 
      timescale: false 
      Vibrato: true
...
```
